FROM ubuntu:18.04

COPY properties/snake-1.0.tar.gz /tmp/
ADD properties/setup.sql /tmp/

ENV DEBIAN_FRONTEND noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apt update \
    && apt-get install -y tzdata \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && apt install apache2 php7.2-mbstring php7.2-gd php7.2-mysql php7.2-gd php7.2-curl php7.2-json php7.2-cgi php7.2 libapache2-mod-php7.2 mysql-server -y \
    && sed -i "s/DocumentRoot \/var\/www\/html/DocumentRoot \/var\/www\/html\/public/g" /etc/apache2/sites-available/000-default.conf \
    && sed -i "s/;extension=mbstring/extension=mbstring/g" /etc/php/7.2/apache2/php.ini \
    && cd /tmp \
    && tar -xvf /tmp/snake-1.0.tar.gz \
    && cp -r snake-1.0/* /var/www/html/ \
    && chown www-data:www-data -R /var/www/html \
    && service mysql start \
    && mysql -uroot -proot < /tmp/setup.sql \
    && sed -i "s/bind-address/#bind-address/g" /etc/mysql/mysql.conf.d/mysqld.cnf \
    && service mysql restart \
    && rm -rf /tmp/* \
    && a2enmod rewrite \
    && sed -i '/Directory \/var\/www\//{:a;n;s/AllowOverride None/AllowOverride All/g;/\/Directory/!ba}' /etc/apache2/apache2.conf \
    && service apache2 restart

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y openssh-server \
    && apt-get clean \
    && mkdir -p /var/run/sshd \
    && echo 'root:thisisadminspasswordofsnakesql' | chpasswd \
    && sed -i 's/#*PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config \
    && sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd \
    && rm -rf ROOT docs examples host-manager manager

ADD properties/web.sh /
RUN apt install curl -y
CMD ["bash", "-c", "echo 1 && bash /web.sh"]
HEALTHCHECK --interval=20s --timeout=5s \
  CMD curl -fs http://localhost/ || exit 1
